---
title: "Nick Stapleton"
url: "https://www.nickstapleton.me"
masthead_title: " "
logo: "/assets/images/nslsm.png"
email: "nickstapleton@gmail.com"
description: "Writing about Logos Bible Software, ministry, theology, and discipleship"
twitter_username: "nickstapleton"
twitter:
  username: "nickstapleton"
github_username: ''
minimal_mistakes_skin: default
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
og_image: "/assets/images/nslsm.png"
teaser: "/assets/images/nslsm.png"
permalink: "/:title/"
paginate: "10"
paginate_path: /page:num/
timezone: America/Denver
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  name: "Nick Stapleton"
  avatar: "/assets/images/2025Nick.png"
  bio: "Seeking to surrender all of life for all of life to Jesus"
  location: "Colorado"
  links:
  - label: "YouTube"
    icon: "fab fa-youtube"
    url: "https://youtube.com/nickstapleton"
  - label: "Instagram"
    icon: "fab fa-instagram"
    url: "https://instagram.com/nickstapleton"
  - label: "Buy Me a Coffee"
    icon: "fas fa-mug-hot"
    color: "#833AB4"
    url: "https://nickstapleton.kit.com/products/tip"
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/    
footer:
  links:
  - label: "YouTube"
    icon: "fab fa-youtube"
    url: "https://youtube.com/nickstapleton"
  - label: "Instagram"
    icon: "fab fa-instagram"
    url: "https://instagram.com/nickstapleton"
  - label: "Buy Me a Coffee"
    icon: "fas fa-mug-hot"
    url: "https://nickstapleton.kit.com/products/tip"
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
    show_date: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
# _portfolio
- scope:
    type: portfolio
  values:
    layout: single
    author_profile: true
    share: true 
    read_time: true
    comments: true
    related: true
    show_date: true
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-941DDE34TS"
    anonymize_ip: false # default
